rules:
  default:
    protection:
      required_status_checks:
        strict: true
        contexts:
          - DCO
          - "Testing: ceph-ansible PR Pipeline"
      required_pull_request_reviews:
        required_approving_review_count: 1
    automated_backport_labels:
      backport-stable-3.0: stable-3.0
      backport-stable-3.1: stable-3.1
    disabling_label: DNM
